sudo: true
language: bash
dist: trusty
before_install:
  - scversion="stable" # or "v0.4.7", or "latest"
  - wget "https://storage.googleapis.com/shellcheck/shellcheck-$scversion.linux.x86_64.tar.xz"
  - tar --xz -xvf "shellcheck-$scversion.linux.x86_64.tar.xz"
  - shellcheck() { "shellcheck-$scversion/shellcheck" "$@"; }
  - export PATH=$PATH:/shellcheck-$scversion/
  - sudo apt-get -qq update
  - sudo apt-get install -f
  - sudo apt-get -y install tmux
before_script: 
  - make install
script: 
  - make test
